
version: 2

models:
    - name: test_dbt_model
      description: "A test dbt model keywords"
     

sources: 
    - name: prescricao
      database: production
      tables:
          - name: df_sanofi_doencas_keywords
